language: cpp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install gcc-4.8

install:
  gcc kursach.cpp -o kursach && ./kursach
