language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-multilib
            - libc6:i386

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
  - g++ -Wall kursach.cpp -o kursach
